/**
 * Antigravity Chinese Localization - Constants & Mappings
 */

// 1. 时间单位映射
const UNIT_MAP_CN = {
  'mo': '个月前',
  'month': '个月前',
  'months': '个月前',
  'd': '天前',
  'day': '天前',
  'days': '天前',
  'm': '分钟前',
  'min': '分钟前',
  'mins': '分钟前',
  'minute': '分钟前',
  'minutes': '分钟前',
  'h': '小时前',
  'hr': '小时前',
  'hrs': '小时前',
  'hour': '小时前',
  'hours': '小时前',
  's': '秒前',
  'sec': '秒前',
  'secs': '秒前',
  'second': '秒前',
  'seconds': '秒前',
  'y': '年前',
  'yr': '年前',
  'yrs': '年前',
  'year': '年前',
  'years': '年前'
};

// 2. 耗时动作前缀
const ACTION_TIMER_PREFIX = {
  'worked for': '工作耗时: ',
  'working for': '工作中: ',
  'thought for': '思考耗时: ',
  'thinking for': '思考中: ',
  'ran for': '执行耗时: ',
  'running for': '已运行: ',
  'waited for': '等待耗时: ',
  'waiting for': '等待中: ',
  'took': '耗时: '
};

// 3. 动作动词映射
const ACTION_MAP = {
  'running': '正在运行',
  'ran': '已运行',
  'run': '运行',
  'executing': '正在执行',
  'executed': '已执行',
  'execute': '执行',
  'exploring': '正在探索',
  'explored': '已探索',
  'explore': '探索',
  'searching': '正在搜索',
  'searched': '已搜索',
  'search': '搜索',
  'reading': '正在读取',
  'read': '已读取',
  'editing': '正在编辑',
  'edited': '已编辑',
  'edit': '编辑',
  'creating': '正在创建',
  'created': '已创建',
  'create': '创建',
  'modifying': '正在修改',
  'modified': '已修改',
  'modify': '修改',
  'deleting': '正在删除',
  'deleted': '已删除',
  'delete': '删除',
  'viewing': '正在查看',
  'viewed': '已查看',
  'view': '查看',
  'analyzing': '正在分析',
  'analyzed': '已分析',
  'analyze': '分析',
  'checking': '正在检查',
  'checked': '已检查',
  'check': '检查',
  'generating': '正在生成',
  'generated': '已生成',
  'generate': '生成',
  'scanning': '正在扫描',
  'scanned': '已扫描',
  'scan': '扫描',
  'finding': '正在查找',
  'found': '已找到',
  'find': '查找',
  'testing': '正在测试',
  'tested': '已测试',
  'test': '测试',
  'building': '正在构建',
  'built': '已构建',
  'build': '构建',
  'compiling': '正在编译',
  'compiled': '已编译',
  'compile': '编译',
  'installing': '正在安装',
  'installed': '已安装',
  'install': '安装',
  'updating': '正在更新',
  'updated': '已更新',
  'update': '更新',
  'cleaning': '正在清理',
  'cleaned': '已清理',
  'clean': '清理',
  'saving': '正在保存',
  'saved': '已保存',
  'save': '保存',
  'loading': '正在加载',
  'loaded': '已加载',
  'load': '加载',
  'fetching': '正在获取',
  'fetched': '已获取',
  'fetch': '获取',
  'downloading': '正在下载',
  'downloaded': '已下载',
  'download': '下载',
  'uploading': '正在上传',
  'uploaded': '已上传',
  'upload': '上传',
  'resolving': '正在解析',
  'resolved': '已解析',
  'resolve': '解析',
  'processing': '正在处理',
  'processed': '已处理',
  'process': '处理',
  'calling': '正在调用',
  'called': '已调用',
  'call': '调用',
  'invoking': '正在调用',
  'invoked': '已调用',
  'invoke': '调用',
  'sending': '正在发送',
  'sent': '已发送',
  'send': '发送',
  'killing': '正在终止',
  'killed': '已终止',
  'kill': '终止',
  'stopping': '正在停止',
  'stopped': '已停止',
  'stop': '停止',
  'working': '工作中',
  'worked': '已工作',
  'work': '工作',
  'thinking': '深度思考',
  'thought': '已思考',
  'think': '思考',
  'waiting': '等待中',
  'waited': '等待耗时'
};

// 4. 对象名词映射（含单复数）
const OBJECT_MAP = {
  'command': '条命令',
  'commands': '条命令',
  'file': '个文件',
  'files': '个文件',
  'search': '次搜索',
  'searches': '次搜索',
  'directory': '个目录',
  'directories': '个目录',
  'folder': '个文件夹',
  'folders': '个文件夹',
  'url': '个链接',
  'urls': '个链接',
  'repo': '个仓库',
  'repos': '个仓库',
  'repository': '个仓库',
  'repositories': '个仓库',
  'commit': '次提交',
  'commits': '次提交',
  'branch': '个分支',
  'branches': '个分支',
  'diff': '处差异',
  'diffs': '处差异',
  'patch': '个补丁',
  'patches': '个补丁',
  'document': '个文档',
  'documents': '个文档',
  'page': '个页面',
  'pages': '个页面',
  'task': '个任务',
  'tasks': '个任务',
  'subagent': '个子智能体',
  'subagents': '个子智能体',
  'agent': '个智能体',
  'agents': '个智能体',
  'process': '个进程',
  'processes': '个进程',
  'job': '个作业',
  'jobs': '个作业',
  'worker': '个工作进程',
  'workers': '个工作进程',
  'tool': '个工具',
  'tools': '个工具',
  'artifact': '个产物',
  'artifacts': '个产物',
  'project': '个项目',
  'projects': '个项目',
  'script': '个脚本',
  'scripts': '个脚本',
  'test': '项测试',
  'tests': '项测试',
  'result': '个结果',
  'results': '个结果',
  'error': '个错误',
  'errors': '个错误',
  'warning': '个警告',
  'warnings': '个警告',
  'item': '项',
  'items': '项',
  'step': '步',
  'steps': '步',
  'line': '行',
  'lines': '行',
  'package': '个软件包',
  'packages': '个软件包',
  'dependency': '个依赖',
  'dependencies': '个依赖',
  'rule': '条规则',
  'rules': '条规则',
  'skill': '项技能',
  'skills': '项技能',
  'call': '次调用',
  'calls': '次调用',
  'request': '个请求',
  'requests': '个请求',
  'query': '次查询',
  'queries': '次查询',
  'token': '个 Token',
  'tokens': '个 Token',
  'model': '个模型',
  'models': '个模型'
};

// 5. 实体映射
const ENTITY_MAP = {
  'task': '个任务',
  'tasks': '个任务',
  'subagent': '个子智能体',
  'subagents': '个子智能体',
  'agent': '个智能体',
  'agents': '个智能体',
  'command': '条命令',
  'commands': '条命令',
  'process': '个进程',
  'processes': '个进程',
  'job': '个作业',
  'jobs': '个作业',
  'worker': '个工作进程',
  'workers': '个工作进程',
  'tool': '个工具',
  'tools': '个工具',
  'artifact': '个产物',
  'artifacts': '个产物',
  'change': '处更改',
  'changes': '处更改',
  'error': '个错误',
  'errors': '个错误',
  'warning': '个警告',
  'warnings': '个警告',
  'result': '个结果',
  'results': '个结果',
  'item': '项',
  'items': '项',
  'query': '次查询',
  'queries': '次查询'
};

// 6. 状态映射
const STATE_MAP = {
  'running': '运行中',
  'active': '活跃中',
  'completed': '已完成',
  'finished': '已完成',
  'failed': '失败',
  'stopped': '已停止',
  'idle': '空闲',
  'waiting': '等待中',
  'pending': '等待中',
  'queued': '排队中',
  'paused': '已暂停',
  'selected': '已选'
};

// 7. 职业与智能体角色后缀
const ROLE_SUFFIX_MAP = {
  'investigator': '调研员',
  'researcher': '研究员',
  'analyzer': '分析师',
  'analyst': '分析师',
  'optimizer': '优化师',
  'engineer': '工程师',
  'architect': '架构师',
  'debugger': '调试专家',
  'reviewer': '审查专家',
  'fixer': '修复专家',
  'specialist': '专家',
  'expert': '专家',
  'developer': '开发者',
  'tester': '测试员',
  'auditor': '审计师',
  'scanner': '扫描器',
  'builder': '构建器',
  'validator': '验证器',
  'coordinator': '协调员',
  'planner': '规划师',
  'worker': '工作进程',
  'agent': '智能体',
  'assistant': '助手',
  'profiler': '分析专家',
  'checker': '检查员',
  'creator': '创建者',
  'generator': '生成器',
  'monitor': '监控器',
  'collector': '收集器',
  'extractor': '提取器',
  'cleaner': '清理器',
  'manager': '管理器',
  'director': '主管',
  'lead': '主管'
};

// 8. 角色修饰词映射
const MODIFIER_MAP = {
  'deep': '深度',
  'fast': '快速',
  'quick': '极速',
  'technical': '技术',
  'feasibility': '可行性',
  'performance': '性能',
  'security': '安全',
  'frontend': '前端',
  'backend': '后端',
  'database': '数据库',
  'codebase': '代码库',
  'code': '代码',
  'memory': '内存',
  'leak': '泄漏',
  'layout': '布局',
  'accessibility': '无障碍',
  'a11y': '无障碍',
  'ui': 'UI',
  'ux': '用户体验',
  'api': 'API',
  'network': '网络',
  'system': '系统',
  'architecture': '架构',
  'schema': '架构',
  'workflow': '工作流',
  'data': '数据',
  'ai': 'AI',
  'portrait': '人像',
  'fidelity': '保真度',
  'style': '风格',
  'color': '色彩',
  'audio': '音频',
  'video': '视频',
  'image': '图像',
  'multimodal': '多模态',
  'semantic': '语义',
  'prompt': '提示词',
  'agentic': '智能体',
  'context': '上下文',
  'token': 'Token',
  'test': '测试',
  'unit': '单元',
  'integration': '集成',
  'e2e': '端到端',
  'quality': '质量',
  'compliance': '合规',
  'async': '异步',
  'concurrency': '并发',
  'vulnerability': '漏洞',
  'vulnerabilities': '漏洞'
};

// 9. 面板徽标映射
const PANE_BADGE_MAP = {
  'subagents': '子智能体',
  'files changed': '已修改文件',
  'artifacts': '产物',
  'uploads': '已上传文件',
  'background tasks': '后台任务',
  'mcp servers': 'MCP 服务',
  'skills': '技能'
};

module.exports = {
  UNIT_MAP_CN,
  ACTION_TIMER_PREFIX,
  ACTION_MAP,
  OBJECT_MAP,
  ENTITY_MAP,
  STATE_MAP,
  ROLE_SUFFIX_MAP,
  MODIFIER_MAP,
  PANE_BADGE_MAP
};
