/**
 * Antigravity Chinese Localization - Build Pipeline
 * 1. 读取并校验 src/dictionary/*.json 模块化词典
 * 2. 合并词典、去重、排重与键值校验
 * 3. 嵌入构词法合成器、动态模式匹配、安全观察者引擎
 * 4. 全局编译转译为纯 7-bit ASCII \uXXXX 序列，根治 Windows GBK/CP936 乱码
 * 5. 输出自包含的独立运行时补丁 dist/patch-payload.js
 */

const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const srcDir = path.join(rootDir, 'src');
const dictDir = path.join(srcDir, 'dictionary');
const distDir = path.join(rootDir, 'dist');
const outputFile = path.join(distDir, 'patch-payload.js');

function toAsciiUnicode(str) {
  return str.replace(/[^\x00-\x7F]/g, char => {
    const hex = char.charCodeAt(0).toString(16).padStart(4, '0');
    return '\\u' + hex;
  });
}

function build() {
  console.log('====================================================');
  console.log('   Antigravity Chinese Localization Build Pipeline  ');
  console.log('====================================================\n');

  // 1. 读取并合并所有词典
  const dictFiles = [
    'actions.json',
    'sidebar.json',
    'settings.json',
    'subagents.json',
    'units.json',
    'tools.json',
    'common.json'
  ];

  const mergedDict = {};
  let totalEntries = 0;
  let duplicates = 0;

  for (const filename of dictFiles) {
    const filePath = path.join(dictDir, filename);
    if (!fs.existsSync(filePath)) {
      console.warn(`[WARN] File not found: ${filename}`);
      continue;
    }

    try {
      const content = fs.readFileSync(filePath, 'utf8');
      const data = JSON.parse(content);
      const keys = Object.keys(data);
      console.log(`[DICT] Loaded ${filename.padEnd(16)} (${keys.length} keys)`);

      for (const [k, v] of Object.entries(data)) {
        if (mergedDict[k] && mergedDict[k] !== v) {
          console.warn(`[WARN] Duplicate key override in ${filename}: "${k}" -> "${v}" (previous: "${mergedDict[k]}")`);
          duplicates++;
        }
        mergedDict[k] = v;
        totalEntries++;
      }
    } catch (e) {
      console.error(`[ERROR] Failed to parse JSON: ${filename}`, e);
      process.exit(1);
    }
  }

  const finalKeys = Object.keys(mergedDict);
  console.log(`\n[STAT] Total merged unique keys: ${finalKeys.length} (Duplicates/Overrides: ${duplicates})`);

  // 2. 读取引擎模块
  const constants = require('../src/engine/constants');
  const { DYNAMIC_TEMPLATES } = require('../src/engine/templates');

  // 3. 构建单文件闭包脚本
  const payloadBanner = `// Antigravity Chinese Localization Patch\n// Compiled at: ${new Date().toISOString()}\n// Generated by: Antigravity Chinese Localization Pipeline\n`;

  const clientTemplate = `(function() {
  'use strict';

  // 1. Static Translation Dictionary (Pure ASCII Unicode Escapes)
  const dictionary = ${JSON.stringify(mergedDict, null, 2)};

  const lowerDictionary = {};
  for (const [k, v] of Object.entries(dictionary)) {
    lowerDictionary[k.toLowerCase()] = v;
  }

  // 2. Dynamic Templates
  const DYNAMIC_TEMPLATES = [
    // Subagent Role Hierarchy
    {
      regex: /^(Deep Investigator|Technical Feasibility Investigator|Codebase Researcher|Database Debugger|Code Reviewer|Bug Fixer)\\s+(L\\d+|Worker\\s+\\d+|#\\d+)$/i,
      format: (m) => {
        const roleMap = {
          'deep investigator': '\\u6df1\\u5ea6\\u8c03\\u7814\\u5458',
          'technical feasibility investigator': '\\u6280\\u672f\\u53ef\\u884c\\u6027\\u5206\\u6790\\u5e08',
          'codebase researcher': '\\u4ee3\\u7801\\u5e93\\u8c03\\u7814\\u5458',
          'database debugger': '\\u6570\\u636e\\u5e93\\u8c03\\u8bd5\\u4e13\\u5bb6',
          'code reviewer': '\\u4ee3\\u7801\\u5ba1\\u67e5\\u4e13\\u5bb6',
          'bug fixer': '\\u7f3a\\u9677\\u4fee\\u590d\\u4e13\\u5bb6'
        };
        const r = roleMap[m[1].toLowerCase()] || m[1];
        return \`\${r} \${m[2]}\`;
      }
    },
    { regex: /^Send\\s+feedback\\s+as\\s+(.+)$/i, format: (m) => \`\\u4ee5 \${m[1]} \\u7684\\u8eab\\u4efd\\u53d1\\u9001\\u53cd\\u9988\` },
    { regex: /^Learn\\s+more\\s+about\\s+(.+)$/i, format: (m) => \`\\u4e86\\u89e3\\u5173\\u4e8e \${m[1]} \\u7684\\u66f4\\u591a\\u4fe1\\u606f\` },
    { regex: /^Open\\s+(.+)\\s+Preferences$/i, format: (m) => \`\\u6253\\u5f00 \${m[1]} \\u504f\\u597d\\u8bbe\\u7f6e\` },
    { regex: /^Open\\s+(.+)\\s+Settings$/i, format: (m) => \`\\u6253\\u5f00 \${m[1]} \\u8bbe\\u7f6e\` },
    { regex: /^Configure\\s+(.+)$/i, format: (m) => \`\\u914d\\u7f6e \${m[1]}\` },
    { regex: /^Manage\\s+(.+)$/i, format: (m) => \`\\u7ba1\\u7406 \${m[1]}\` },
    { regex: /^Enable\\s+(.+)$/i, format: (m) => \`\\u542f\\u7528 \${m[1]}\` },
    { regex: /^Disable\\s+(.+)$/i, format: (m) => \`\\u7981\\u7528 \${m[1]}\` },
    { regex: /^Choose\\s+a\\s+predefined\\s+(.+)\\s+for\\s+the\\s+agent\\.(.*)$/i, format: (m) => \`\\u4e3a\\u667a\\u80fd\\u4f53\\u9009\\u62e9\\u9884\\u8bbe\\u7684 \${m[1]}\\u3002\${m[2]}\` },
    { regex: /^Scan\\s+the\\s+code\\s+to\\s+(.+)$/i, format: (m) => \`\\u626b\\u63cf\\u4e8c\\u7ef4\\u7801\\u4ee5 \${m[1]}\` },
    { regex: /^Created\\s+(\\d+)\\s+files?$/i, format: (m) => \`\\u5df2\\u521b\\u5efa \${m[1]} \\u4e2a\\u6587\\u4ef6\` },
    { regex: /^Edited\\s+(\\d+)\\s+files?$/i, format: (m) => \`\\u5df2\\u7f16\\u8f91 \${m[1]} \\u4e2a\\u6587\\u4ef6\` },
    { regex: /^Read\\s+(\\d+)\\s+files?$/i, format: (m) => \`\\u5df2\\u8bfb\\u53d6 \${m[1]} \\u4e2a\\u6587\\u4ef6\` },
    { regex: /^Searched\\s+(\\d+)\\s+files?$/i, format: (m) => \`\\u5df2\\u641c\\u7d22 \${m[1]} \\u4e2a\\u6587\\u4ef6\` },
    { regex: /^Found\\s+(\\d+)\\s+results?$/i, format: (m) => \`\\u627e\\u5230 \${m[1]} \\u4e2a\\u7ed3\\u679c\` },
    { regex: /^Found\\s+(\\d+)\\s+files?$/i, format: (m) => \`\\u627e\\u5230 \${m[1]} \\u4e2a\\u6587\\u4ef6\` },
    { regex: /^Found\\s+(\\d+)\\s+matches?$/i, format: (m) => \`\\u627e\\u5230 \${m[1]} \\u4e2a\\u5339\\u914d\\u9879\` },
    { regex: /^Sent\\s+message\\s+to\\s+(.+)$/i, format: (m) => \`\\u5df2\\u53d1\\u9001\\u6d88\\u606f\\u7ed9 \${m[1]}\` },
    { regex: /^Received\\s+message\\s+from\\s+(.+)$/i, format: (m) => \`\\u6536\\u5230\\u6765\\u81ea \${m[1]} \\u7684\\u6d88\\u606f\` },
    { regex: /^Waiting\\s+for\\s+(.+)$/i, format: (m) => \`\\u7b49\\u5f85 \${m[1]}\` },
    { regex: /^Blocked\\s+by\\s+(.+)$/i, format: (m) => \`\\u88ab \${m[1]} \\u963b\\u585e\` },
    { regex: /^(\\d+)\\s+of\\s+(\\d+)\\s+completed$/i, format: (m) => \`\${m[1]}/\${m[2]} \\u5df2\\u5b8c\\u6210\` },
    { regex: /^Step\\s+(\\d+)\\s+of\\s+(\\d+)$/i, format: (m) => \`\\u6b65\\u9aa4 \${m[1]}/\${m[2]}\` },
    { regex: /^Spawned\\s+(\\d+)\\s+subagents?$/i, format: (m) => \`\\u5df2\\u751f\\u6210 \${m[1]} \\u4e2a\\u5b50\\u667a\\u80fd\\u4f53\` },
    { regex: /^Invoked\\s+(\\d+)\\s+subagents?$/i, format: (m) => \`\\u5df2\\u8c03\\u7528 \${m[1]} \\u4e2a\\u5b50\\u667a\\u80fd\\u4f53\` },
    { regex: /^Viewing\\s+(.+)$/i, format: (m) => \`\\u6b63\\u5728\\u67e5\\u770b \${m[1]}\` },
    { regex: /^Editing\\s+(.+)$/i, format: (m) => \`\\u6b63\\u5728\\u7f16\\u8f91 \${m[1]}\` },
    { regex: /^Creating\\s+(.+)$/i, format: (m) => \`\\u6b63\\u5728\\u521b\\u5efa \${m[1]}\` },
    { regex: /^Reading\\s+(.+)$/i, format: (m) => \`\\u6b63\\u5728\\u8bfb\\u53d6 \${m[1]}\` },
    { regex: /^Writing\\s+(.+)$/i, format: (m) => \`\\u6b63\\u5728\\u5199\\u5165 \${m[1]}\` },
    { regex: /^Searching\\s+(.+)$/i, format: (m) => \`\\u6b63\\u5728\\u641c\\u7d22 \${m[1]}\` },
    { regex: /^Analyzing\\s+(.+)$/i, format: (m) => \`\\u6b63\\u5728\\u5206\\u6790 \${m[1]}\` },
    { regex: /^Fetching\\s+(.+)$/i, format: (m) => \`\\u6b63\\u5728\\u83b7\\u53d6 \${m[1]}\` },
    { regex: /^Generating\\s+(.+)$/i, format: (m) => \`\\u6b63\\u5728\\u751f\\u6210 \${m[1]}\` },
    { regex: /^Scheduling\\s+(.+)$/i, format: (m) => \`\\u6b63\\u5728\\u8c03\\u5ea6 \${m[1]}\` },
    { regex: /^Invoking\\s+(.+)$/i, format: (m) => \`\\u6b63\\u5728\\u8c03\\u7528 \${m[1]}\` },
    { regex: /^Launching\\s+(.+)$/i, format: (m) => \`\\u6b63\\u5728\\u542f\\u52a8 \${m[1]}\` },
    { regex: /^Listing\\s+(.+)$/i, format: (m) => \`\\u6b63\\u5728\\u5217\\u51fa \${m[1]}\` },
    { regex: /^Navigating\\s+(.+)$/i, format: (m) => \`\\u6b63\\u5728\\u5bfc\\u822a \${m[1]}\` },
    { regex: /^Defining\\s+(.+)$/i, format: (m) => \`\\u6b63\\u5728\\u5b9a\\u4e49 \${m[1]}\` },
    { regex: /^Spawning\\s+(.+)$/i, format: (m) => \`\\u6b63\\u5728\\u751f\\u6210 \${m[1]}\` },
    { regex: /^Sending\\s+(.+)$/i, format: (m) => \`\\u6b63\\u5728\\u53d1\\u9001 \${m[1]}\` },
    { regex: /^Calling\\s+(.+)$/i, format: (m) => \`\\u6b63\\u5728\\u8c03\\u7528 \${m[1]}\` },
    { regex: /^Replacing\\s+(.+)$/i, format: (m) => \`\\u6b63\\u5728\\u66ff\\u6362 \${m[1]}\` },
    { regex: /^Killing\\s+(.+)$/i, format: (m) => \`\\u6b63\\u5728\\u7ec8\\u6b62 \${m[1]}\` },
    { regex: /^Setting\\s+(.+)$/i, format: (m) => \`\\u6b63\\u5728\\u8bbe\\u7f6e \${m[1]}\` },
    { regex: /^Signed\\s+in\\s+as\\s+(.+)$/i, format: (m) => \`\\u5df2\\u767b\\u5f55\\u4e3a \${m[1]}\` }
  ];

  // 3. Constants & Mapping Dictionaries
  const UNIT_MAP_CN = ${JSON.stringify(constants.UNIT_MAP_CN, null, 2)};
  const ACTION_TIMER_PREFIX = ${JSON.stringify(constants.ACTION_TIMER_PREFIX, null, 2)};
  const ACTION_MAP = ${JSON.stringify(constants.ACTION_MAP, null, 2)};
  const OBJECT_MAP = ${JSON.stringify(constants.OBJECT_MAP, null, 2)};
  const ENTITY_MAP = ${JSON.stringify(constants.ENTITY_MAP, null, 2)};
  const STATE_MAP = ${JSON.stringify(constants.STATE_MAP, null, 2)};
  const ROLE_SUFFIX_MAP = ${JSON.stringify(constants.ROLE_SUFFIX_MAP, null, 2)};
  const MODIFIER_MAP = ${JSON.stringify(constants.MODIFIER_MAP, null, 2)};
  const PANE_BADGE_MAP = ${JSON.stringify(constants.PANE_BADGE_MAP, null, 2)};

  // 4. Strict Safety Bypass Elements & Ancestor Selectors
  const IGNORE_TAGS = new Set([
    'SCRIPT', 'STYLE', 'NOSCRIPT', 'TEMPLATE', 'CANVAS',
    'SVG', 'MATH', 'OBJECT', 'EMBED'
  ]);

  const CODE_OR_INPUT_TAGS = new Set([
    'PRE', 'CODE', 'KBD', 'SAMP', 'VAR', 'TEXTAREA'
  ]);

  const BUTTON_INPUT_TYPES = new Set([
    'button', 'submit', 'reset'
  ]);

  const SAFE_ATTRS = ['placeholder', 'title', 'aria-label', 'data-tooltip', 'data-title', 'data-description', 'tooltip', 'alt'];

  const BYPASS_ANCESTOR_SELECTOR = [
    '.monaco-editor',
    '.view-lines',
    '.monaco-list-row',
    '.cm-editor',
    '.cm-content',
    '.editor-instance',
    '.monaco-tokenized-source',
    'pre',
    'code',
    'kbd',
    'samp',
    'var',
    '.code-block',
    '.hljs',
    '.syntax-highlighted',
    '.highlight',
    '.terminal',
    '.xterm',
    '.xterm-screen',
    '.xterm-viewport',
    '.terminal-wrapper',
    'textarea',
    '[contenteditable="true"]',
    '[contenteditable=""]',
    '[contenteditable]:not([contenteditable="false"])',
    '[data-no-translate]',
    '[translate="no"]',
    'svg',
    'canvas'
  ].join(', ');

  // 5. Helper Functions
  function normalize(str) {
    if (!str) return '';
    return str.replace(/\\u00a0/g, ' ').replace(/\\s+/g, ' ');
  }

  function formatDur(str) {
    if (!str) return '';
    return str
      .replace(/(\\d+(?:\\.\\d+)?)\\s*(?:years?|yrs?|y)\\b/gi, '$1\\u5e74')
      .replace(/(\\d+(?:\\.\\d+)?)\\s*(?:months?|mo)\\b/gi, '$1\\u4e2a\\u6708')
      .replace(/(\\d+(?:\\.\\d+)?)\\s*(?:days?|d)\\b/gi, '$1\\u5929')
      .replace(/(\\d+(?:\\.\\d+)?)\\s*(?:hours?|hrs?|h)\\b/gi, '$1\\u5c0f\\u65f6')
      .replace(/(\\d+(?:\\.\\d+)?)\\s*(?:minutes?|mins?|m)\\b/gi, '$1\\u5206\\u949f')
      .replace(/(\\d+(?:\\.\\d+)?)\\s*(?:seconds?|secs?|s)\\b/gi, '$1\\u79d2')
      .replace(/(\\d+(?:\\.\\d+)?)\\s*(?:milliseconds?|millisecs?|ms)\\b/gi, '$1\\u6beb\\u79d2')
      .replace(/\\s+/g, ' ')
      .trim();
  }

  function formatTimerUnit(unit) {
    if (!unit) return '\\u79d2';
    const u = unit.toLowerCase();
    if (u === 'ms' || u.startsWith('millisec')) return '\\u6beb\\u79d2';
    if (u === 'm' || u.startsWith('min')) return '\\u5206\\u949f';
    if (u === 'h' || u.startsWith('hour') || u === 'hr' || u === 'hrs') return '\\u5c0f\\u65f6';
    if (u === 'd' || u.startsWith('day')) return '\\u5929';
    return '\\u79d2';
  }

  // 6. Subagent Role Morphological Synthesizer
  function synthesizeRole(text) {
    if (!text || typeof text !== 'string') return null;
    const trimmed = text.trim();

    let levelSuffix = '';
    const levelMatch = trimmed.match(/^(.*?)\\s+((?:L|V|#|Worker|Node)\\s*\\d+)$/i);
    let core = trimmed;
    if (levelMatch) {
      core = levelMatch[1].trim();
      levelSuffix = ' ' + levelMatch[2];
    }

    const words = core.split(/\\s+/);
    if (words.length < 2) return null;

    const lastWord = words[words.length - 1].toLowerCase();
    const roleCn = ROLE_SUFFIX_MAP[lastWord];
    if (!roleCn) return null;

    const translatedWords = [];
    for (let i = 0; i < words.length - 1; i++) {
      const rawWord = words[i];
      const w = rawWord.toLowerCase();
      const modCn = MODIFIER_MAP[w];
      if (modCn) {
        translatedWords.push(modCn);
      } else {
        translatedWords.push(rawWord);
      }
    }

    translatedWords.push(roleCn);
    return translatedWords.join('') + levelSuffix;
  }

  // 7. Dynamic Pattern Matcher Pipeline
  function matchDynamicPatterns(trimmed) {
    let m;

    let symbolSuffix = '';
    const arrowMatch = trimmed.match(/^(.*?)([\\s›»>ˇv^▼▶◀▲]+)$/);
    let coreText = trimmed;
    if (arrowMatch && arrowMatch[1].trim()) {
      coreText = arrowMatch[1].trim();
      symbolSuffix = arrowMatch[2];
    }

    // Action Timers (e.g. Worked for 6s, Thought for 1s, Ran for 2s)
    if ((m = coreText.match(/^(worked\\s+for|working\\s+for|thought\\s+for|thinking\\s+for|ran\\s+for|running\\s+for|waited\\s+for|waiting\\s+for|took)\\s+(.+)$/i))) {
      const key = m[1].toLowerCase().replace(/\\s+/g, ' ');
      const pfx = ACTION_TIMER_PREFIX[key] || '\\u8017\\u65f6: ';
      return \`\${pfx}\${formatDur(m[2])}\${symbolSuffix}\`;
    }

    // Single Action-Object Matcher (e.g. "Exploring 1 file", "Running 2 commands")
    const singleActionMatch = coreText.match(/^([a-zA-Z]+)\\s+(\\d+)\\s+([a-zA-Z]+)$/i);
    if (singleActionMatch) {
      const act = ACTION_MAP[singleActionMatch[1].toLowerCase()];
      const obj = OBJECT_MAP[singleActionMatch[3].toLowerCase()];
      if (act && obj) {
        return \`\${act} \${singleActionMatch[2]} \${obj}\${symbolSuffix}\`;
      }
    }

    // Compound Comma-Separated Clauses (e.g. "Exploring 1 file, 1 search")
    if (coreText.includes(',')) {
      const parts = coreText.split(',').map(s => s.trim());
      const transParts = [];
      let allOk = true;

      for (let i = 0; i < parts.length; i++) {
        const part = parts[i];
        const mFull = part.match(/^([a-zA-Z]+)\\s+(\\d+)\\s+([a-zA-Z]+)$/i);
        if (mFull) {
          const act = ACTION_MAP[mFull[1].toLowerCase()];
          const obj = OBJECT_MAP[mFull[3].toLowerCase()];
          if (act && obj) {
            transParts.push(\`\${act} \${mFull[2]} \${obj}\`);
            continue;
          }
        }

        const mCountObj = part.match(/^(\\d+)\\s+([a-zA-Z]+)$/i);
        if (mCountObj) {
          const obj = OBJECT_MAP[mCountObj[2].toLowerCase()];
          if (obj) {
            transParts.push(\`\${mCountObj[1]} \${obj}\`);
            continue;
          }
        }

        allOk = false;
        break;
      }

      if (allOk && transParts.length > 0) {
        return transParts.join('\\uff0c') + symbolSuffix;
      }
    }

    // Relative Times
    if (/^just\\s+now$/i.test(trimmed)) return '\\u521a\\u521a';
    if (/^a\\s+few\\s+seconds\\s+ago$/i.test(trimmed)) return '\\u51e0\\u79d2\\u524d';
    if (/^a\\s+minute\\s+ago$/i.test(trimmed)) return '1\\u5206\\u949f\\u524d';
    if (/^an\\s+hour\\s+ago$/i.test(trimmed)) return '1\\u5c0f\\u65f6\\u524d';
    if (/^a\\s+day\\s+ago$/i.test(trimmed)) return '1\\u5929\\u524d';
    if (/^today$/i.test(trimmed)) return '\\u4eca\\u5929';
    if (/^yesterday$/i.test(trimmed)) return '\\u6628\\u5929';

    if (trimmed.startsWith('Today ')) return trimmed.replace('Today ', '\\u4eca\\u5929 ');
    if (trimmed.startsWith('Yesterday ')) return trimmed.replace('Yesterday ', '\\u6628\\u5929 ');

    // Compact Relative Timestamps (e.g. 10d, 5m, 1mo, 2h, 30s)
    if ((m = trimmed.match(/^(\\d+)\\s*(mo|[dmhsy])(?:\\s+ago)?$/i))) {
      const unit = m[2].toLowerCase();
      const cn = UNIT_MAP_CN[unit];
      if (cn) return \`\${m[1]}\${cn}\`;
    }

    // Verbose Relative Timestamps (e.g. 5 minutes ago)
    if ((m = trimmed.match(/^(\\d+)\\s*(months?|days?|hours?|hrs?|minutes?|mins?|seconds?|secs?|years?|yrs?)\\s+ago$/i))) {
      const unit = m[2].toLowerCase();
      const cn = UNIT_MAP_CN[unit];
      if (cn) return \`\${m[1]}\${cn}\`;
    }

    // Dynamic Pane Badges & Workspace Counters
    if ((m = trimmed.match(/^(Subagents|Files Changed|Artifacts|Uploads|Background Tasks|MCP Servers|Skills)\\s+(\\d+)$/i))) {
      const label = PANE_BADGE_MAP[m[1].toLowerCase()] || m[1];
      return \`\${label} \${m[2]}\`;
    }

    // File change counters
    if ((m = trimmed.match(/^(\\d+)\\s+files?\\s+changed$/i))) return \`\${m[1]} \\u4e2a\\u6587\\u4ef6\\u5df2\\u4fee\\u6539\`;
    if ((m = trimmed.match(/^(\\d+)\\s+files?\\s+modified$/i))) return \`\${m[1]} \\u4e2a\\u6587\\u4ef6\\u5df2\\u4fee\\u6539\`;
    if ((m = trimmed.match(/^(\\d+)\\s+files?\\s+added$/i))) return \`\${m[1]} \\u4e2a\\u6587\\u4ef6\\u5df2\\u6dfb\\u52a0\`;
    if ((m = trimmed.match(/^(\\d+)\\s+files?\\s+deleted$/i))) return \`\${m[1]} \\u4e2a\\u6587\\u4ef6\\u5df2\\u5220\\u9664\`;
    if ((m = trimmed.match(/^(\\d+)\\s+files?$/i))) return \`\${m[1]} \\u4e2a\\u6587\\u4ef6\`;

    // Universal Entity-State Matrix Engine
    if ((m = trimmed.match(/^(\\d+)\\s+([a-zA-Z]+)\\s+([a-zA-Z]+)$/i))) {
      const entity = ENTITY_MAP[m[2].toLowerCase()];
      const state = STATE_MAP[m[3].toLowerCase()];
      if (entity && state) {
        if (m[3].toLowerCase() === 'selected') {
          return \`\\u5df2\\u9009 \${m[1]} \${entity}\`;
        }
        return \`\${m[1]} \${entity}\${state}\`;
      }
    }

    if ((m = trimmed.match(/^(?:no|0)\\s+([a-zA-Z]+)\\s+([a-zA-Z]+)$/i))) {
      const entity = ENTITY_MAP[m[1].toLowerCase()];
      const state = STATE_MAP[m[2].toLowerCase()];
      if (entity && state) {
        const noun = entity.replace(/^[^\\s]*?[个条处项]/, '');
        return \`\\u6682\\u65e0\${state}\\u7684\${noun || entity}\`;
      }
    }

    if ((m = trimmed.match(/^all\\s+([a-zA-Z]+)\\s+([a-zA-Z]+)$/i))) {
      const entity = ENTITY_MAP[m[1].toLowerCase()];
      const state = STATE_MAP[m[2].toLowerCase()];
      if (entity && state) {
        const noun = entity.replace(/^[^\\s]*?[个条处项]/, '');
        return \`\\u5168\\u90e8\${noun || entity}\${state}\`;
      }
    }

    if ((m = trimmed.match(/^(\\d+)\\s+selected$/i))) return \`\\u5df2\\u9009 \${m[1]} \\u9879\`;
    if ((m = trimmed.match(/^(\\d+)\\s+([a-zA-Z]+)$/i))) {
      const entity = ENTITY_MAP[m[2].toLowerCase()];
      if (entity) {
        return \`\${m[1]} \${entity}\`;
      }
    }

    // Dynamic Templates
    for (let i = 0; i < DYNAMIC_TEMPLATES.length; i++) {
      const tmpl = DYNAMIC_TEMPLATES[i];
      if ((m = trimmed.match(tmpl.regex))) {
        return tmpl.format(m);
      }
    }

    return null;
  }

  // 8. Master Text Translation Dispatcher
  function translateText(text) {
    if (!text || typeof text !== 'string') return null;
    const normalized = normalize(text);
    const trimmed = normalized.trim();
    if (!trimmed) return null;

    // 1. Direct dictionary match (exact)
    if (dictionary[trimmed]) {
      return normalized.replace(trimmed, dictionary[trimmed]);
    }
    if (dictionary[normalized]) {
      return dictionary[normalized];
    }

    // 2. Case-insensitive dictionary fallback
    const lower = trimmed.toLowerCase();
    if (lowerDictionary[lower]) {
      return normalized.replace(trimmed, lowerDictionary[lower]);
    }

    // 3. Robust shortcut suffix detection
    const scMatch = trimmed.match(/^(.+?)\\s+(?:\\()?((?:Ctrl|Cmd|Alt|Shift|⌘|⌥|⇧|⌃)[\\+\\-\\w]+)(?:\\))?$/i);
    if (scMatch) {
      const actionPart = scMatch[1].trim();
      const scPart = scMatch[2];
      const transAction = dictionary[actionPart] || lowerDictionary[actionPart.toLowerCase()] || matchDynamicPatterns(actionPart);
      if (transAction) {
        return normalized.replace(trimmed, \`\${transAction} (\${scPart})\`);
      }
    }

    // 4. Trailing ellipsis fallback
    if (trimmed.endsWith('...') || trimmed.endsWith('…')) {
      const base = trimmed.replace(/\\.{3}$|…$/, '').trim();
      const transBase = dictionary[base] || lowerDictionary[base.toLowerCase()] || matchDynamicPatterns(base);
      if (transBase) {
        return normalized.replace(trimmed, transBase + '...');
      }
    }

    // 5. Universal Subagent Role Morphological Synthesizer Fallback
    const roleSynth = synthesizeRole(trimmed);
    if (roleSynth !== null) {
      return normalized.replace(trimmed, roleSynth);
    }

    // 6. Dynamic regex & template matchers
    const dynamicMatch = matchDynamicPatterns(trimmed);
    if (dynamicMatch !== null) {
      return normalized.replace(trimmed, dynamicMatch);
    }

    return null;
  }

  // 9. Safety Bypass Checks
  function isBypassedElement(el) {
    if (!el || el.nodeType !== 1) return false;
    if (IGNORE_TAGS.has(el.tagName)) return true;
    if (el.isContentEditable) return true;
    if (el.getAttribute && el.getAttribute('contenteditable') === 'true') return true;

    if (el.matches && el.matches(BYPASS_ANCESTOR_SELECTOR)) return true;
    if (el.closest && el.closest(BYPASS_ANCESTOR_SELECTOR)) return true;

    const className = (typeof el.className === 'string') ? el.className : (el.getAttribute ? (el.getAttribute('class') || '') : '');
    if (className) {
      const bypassClasses = ['monaco-editor', 'view-lines', 'monaco-list-row', 'terminal', 'xterm', 'code-block', 'hljs', 'cm-editor', 'cm-content'];
      for (let i = 0; i < bypassClasses.length; i++) {
        if (className.includes(bypassClasses[i])) return true;
      }
    }
    return false;
  }

  function isBypassedNode(node) {
    if (!node) return true;
    if (node.nodeType === 3) {
      const parent = node.parentElement || node.parentNode;
      if (!parent || parent.nodeType !== 1) return false;
      const parentTag = parent.tagName ? parent.tagName.toUpperCase() : '';
      if (IGNORE_TAGS.has(parentTag) || CODE_OR_INPUT_TAGS.has(parentTag)) return true;
      if (parent.isContentEditable) return true;
      if (parent.closest && parent.closest(BYPASS_ANCESTOR_SELECTOR)) return true;
      return isBypassedElement(parent);
    }
    if (node.nodeType === 1) {
      return isBypassedElement(node);
    }
    return false;
  }

  function translateAttributes(el, attrs) {
    if (!el || !el.getAttribute) return;
    for (let i = 0; i < attrs.length; i++) {
      const attr = attrs[i];
      if (el.hasAttribute && el.hasAttribute(attr)) {
        const val = el.getAttribute(attr);
        if (val && typeof val === 'string') {
          const trans = translateText(val);
          if (trans !== null && trans !== val) {
            el.setAttribute(attr, trans);
          }
        }
      }
    }
  }

  // 10. Recursive DOM and Shadow DOM Walker
  function walk(node) {
    if (!node) return;

    if (node.nodeType === 3) {
      if (isBypassedNode(node)) return;
      const text = node.nodeValue;
      if (text && typeof text === 'string') {
        const trans = translateText(text);
        if (trans !== null && trans !== text) {
          node.nodeValue = trans;
        }
      }
      return;
    }

    if (node.nodeType === 11) {
      for (let child = node.firstChild; child; child = child.nextSibling) {
        walk(child);
      }
      return;
    }

    if (node.nodeType === 1) {
      const tag = node.tagName ? node.tagName.toUpperCase() : '';
      if (IGNORE_TAGS.has(tag)) return;

      if (tag === 'TEXTAREA') {
        translateAttributes(node, SAFE_ATTRS);
        return;
      }

      if (tag === 'INPUT') {
        const itype = (node.getAttribute('type') || 'text').toLowerCase();
        if (BUTTON_INPUT_TYPES.has(itype)) {
          translateAttributes(node, [...SAFE_ATTRS, 'value']);
        } else {
          translateAttributes(node, SAFE_ATTRS);
        }
        return;
      }

      const isSelfBypassed = (
        CODE_OR_INPUT_TAGS.has(tag) ||
        (node.matches && node.matches(BYPASS_ANCESTOR_SELECTOR)) ||
        isBypassedElement(node)
      );

      if (isSelfBypassed) {
        translateAttributes(node, SAFE_ATTRS);
        return;
      }

      translateAttributes(node, SAFE_ATTRS);

      if (node.shadowRoot) {
        observeRoot(node.shadowRoot);
        walk(node.shadowRoot);
      }

      for (let child = node.firstChild; child; child = child.nextSibling) {
        walk(child);
      }
    }
  }

  // 11. MutationObserver Setup & Lifecycle
  let observer = null;
  const observedRoots = new WeakSet();
  const observerConfig = {
    childList: true,
    subtree: true,
    characterData: true,
    attributes: true
  };

  function observeRoot(root) {
    if (!root || !observer || observedRoots.has(root)) return;
    try {
      observedRoots.add(root);
      observer.observe(root, observerConfig);
    } catch (e) {}
  }

  function startObserver() {
    if (observer) return;
    if (typeof MutationObserver === 'undefined') return;

    observer = new MutationObserver(mutations => {
      for (let i = 0; i < mutations.length; i++) {
        const m = mutations[i];
        if (m.type === 'childList') {
          for (let j = 0; j < m.addedNodes.length; j++) {
            const added = m.addedNodes[j];
            if (added.nodeType === 1 && added.shadowRoot) {
              observeRoot(added.shadowRoot);
            }
            walk(added);
          }
        } else if (m.type === 'characterData') {
          const node = m.target;
          if (!isBypassedNode(node)) {
            const trans = translateText(node.nodeValue);
            if (trans !== null && trans !== node.nodeValue) {
              node.nodeValue = trans;
            }
          }
        } else if (m.type === 'attributes') {
          const el = m.target;
          if (el.nodeType === 1 && !isBypassedElement(el)) {
            walk(el);
          }
        }
      }
    });

    if (typeof document !== 'undefined') {
      if (document.documentElement) observeRoot(document.documentElement);
      if (document.body) observeRoot(document.body);
    }
  }

  // 12. Hook attachShadow for Web Components
  if (typeof Element !== 'undefined' && Element.prototype && Element.prototype.attachShadow) {
    const origAttachShadow = Element.prototype.attachShadow;
    Element.prototype.attachShadow = function(init) {
      const shadowRoot = origAttachShadow.apply(this, arguments);
      try {
        if (shadowRoot) {
          observeRoot(shadowRoot);
          walk(shadowRoot);
        }
      } catch (e) {}
      return shadowRoot;
    };
  }

  // 13. Periodic Background Micro-Sweep
  function startPeriodicSweep() {
    if (typeof window === 'undefined' || typeof document === 'undefined') return;
    
    const sweep = () => {
      try {
        if (document.documentElement) {
          walk(document.documentElement);
        }
      } catch (e) {}
    };

    window.addEventListener('focus', sweep, { passive: true });
    document.addEventListener('visibilitychange', () => {
      if (document.visibilityState === 'visible') sweep();
    }, { passive: true });
    window.addEventListener('popstate', sweep, { passive: true });
    window.addEventListener('hashchange', sweep, { passive: true });

    setInterval(sweep, 1500);
  }

  // 14. Hook DOM Ready State
  if (typeof document !== 'undefined') {
    const init = () => {
      walk(document.documentElement || document.body);
      startObserver();
      startPeriodicSweep();
    };

    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', init);
    } else {
      init();
    }
  }

  // 15. Global CommonJS Exports for testing & verification
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
      dictionary,
      lowerDictionary,
      DYNAMIC_TEMPLATES,
      UNIT_MAP_CN,
      ACTION_TIMER_PREFIX,
      ACTION_MAP,
      OBJECT_MAP,
      ENTITY_MAP,
      STATE_MAP,
      ROLE_SUFFIX_MAP,
      MODIFIER_MAP,
      PANE_BADGE_MAP,
      normalize,
      formatDur,
      formatTimerUnit,
      synthesizeRole,
      matchDynamicPatterns,
      translateText,
      isBypassedElement,
      isBypassedNode,
      walk,
      startObserver
    };
  }
})();
`;

  // 4. 将包含中文字符的全部代码转换为纯 7-bit ASCII \uXXXX
  const fullCode = payloadBanner + clientTemplate;
  const asciiCode = toAsciiUnicode(fullCode);

  // 5. 校验转换后的文件是否 100% 纯 7-bit ASCII
  for (let i = 0; i < asciiCode.length; i++) {
    const code = asciiCode.charCodeAt(i);
    if (code > 127) {
      console.error(`[FATAL] Non-ASCII byte detected at pos ${i}: charCode=${code}`);
      process.exit(1);
    }
  }

  if (!fs.existsSync(distDir)) {
    fs.mkdirSync(distDir, { recursive: true });
  }

  fs.writeFileSync(outputFile, asciiCode, 'ascii');
  const stat = fs.statSync(outputFile);

  console.log(`\n[SUCCESS] dist/patch-payload.js successfully generated!`);
  console.log(`- Target: ${outputFile}`);
  console.log(`- File size: ${(stat.size / 1024).toFixed(2)} KB`);
  console.log(`- Character encoding: Pure 7-bit ASCII (CP936/GBK Immune)\n`);
}

if (require.main === module) {
  build();
}

module.exports = { build, toAsciiUnicode };
