/**
 * Antigravity Chinese Localization - Build Pipeline
 * 1. 读取并校验 src/dictionary/*.json 模块化词典
 * 2. 合并词典、去重、排重与键值校验
 * 3. 实时读取 src/engine/*.js 模块源码组装为单文件 IIFE，杜绝逻辑脱节
 * 4. 全局编译转译为纯 7-bit ASCII \uXXXX 序列，根治 Windows GBK/CP936 乱码
 * 5. 输出自包含的独立运行时补丁 dist/patch-payload.js
 */

const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const srcDir = path.join(rootDir, 'src');
const dictDir = path.join(srcDir, 'dictionary');
const engineDir = path.join(srcDir, 'engine');
const distDir = path.join(rootDir, 'dist');
const outputFile = path.join(distDir, 'patch-payload.js');

function toAsciiUnicode(str) {
  return str.replace(/[^\x00-\x7F]/g, char => {
    const hex = char.charCodeAt(0).toString(16).padStart(4, '0');
    return '\\u' + hex;
  });
}

function stripCjs(code) {
  return code
    .replace(/^const\s*\{[^}]*\}\s*=\s*require\([^)]*\);?\s*$/gm, '')
    .replace(/^const\s+[a-zA-Z0-9_]+\s*=\s*require\([^)]*\);?\s*$/gm, '')
    .replace(/module\.exports\s*=\s*\{[\s\S]*?\};?/g, '')
    .trim();
}

function build() {
  console.log('====================================================');
  console.log('   Antigravity Chinese Localization Build Pipeline  ');
  console.log('====================================================\n');

  // 1. 读取并合并所有词典
  const dictFiles = [
    'actions.json',
    'sidebar.json',
    'settings.json',
    'subagents.json',
    'units.json',
    'tools.json',
    'common.json'
  ];

  const mergedDict = {};
  let totalEntries = 0;
  let duplicates = 0;

  for (const filename of dictFiles) {
    const filePath = path.join(dictDir, filename);
    if (!fs.existsSync(filePath)) {
      console.warn(`[WARN] File not found: ${filename}`);
      continue;
    }

    try {
      const content = fs.readFileSync(filePath, 'utf8');
      const data = JSON.parse(content);
      const keys = Object.keys(data);
      console.log(`[DICT] Loaded ${filename.padEnd(16)} (${keys.length} keys)`);

      for (const [k, v] of Object.entries(data)) {
        if (mergedDict[k] && mergedDict[k] !== v) {
          console.warn(`[WARN] Duplicate key override in ${filename}: "${k}" -> "${v}" (previous: "${mergedDict[k]}")`);
          duplicates++;
        }
        mergedDict[k] = v;
        totalEntries++;
      }
    } catch (e) {
      console.error(`[ERROR] Failed to parse JSON: ${filename}`, e);
      process.exit(1);
    }
  }

  const finalKeys = Object.keys(mergedDict);
  console.log(`\n[STAT] Total merged unique keys: ${finalKeys.length} (Duplicates/Overrides: ${duplicates})`);

  // 2. 实时读取 src/engine/ 核心模块源码（保证单一真实数据源 SSOT）
  console.log('[ENGINE] Bundling modules from src/engine/...');
  const constants = require('../src/engine/constants');
  const templatesCode = stripCjs(fs.readFileSync(path.join(engineDir, 'templates.js'), 'utf8'));
  const synthesizerCode = stripCjs(fs.readFileSync(path.join(engineDir, 'synthesizer.js'), 'utf8'));
  const matcherCode = stripCjs(fs.readFileSync(path.join(engineDir, 'matcher.js'), 'utf8'));
  const dispatcherCode = stripCjs(fs.readFileSync(path.join(engineDir, 'dispatcher.js'), 'utf8'));
  const observerCode = stripCjs(fs.readFileSync(path.join(engineDir, 'observer.js'), 'utf8'));

  // 3. 构建单文件闭包脚本
  const payloadBanner = `// Antigravity Chinese Localization Patch\n// Compiled at: ${new Date().toISOString()}\n// Generated by: Antigravity Chinese Localization Pipeline\n`;

  const clientTemplate = `(function() {
  'use strict';

  // 1. Static Translation Dictionary
  const dictionary = ${JSON.stringify(mergedDict, null, 2)};

  const lowerDictionary = {};
  for (const [k, v] of Object.entries(dictionary)) {
    lowerDictionary[k.toLowerCase()] = v;
  }

  // 2. Constants & Mappings
  const UNIT_MAP_CN = ${JSON.stringify(constants.UNIT_MAP_CN, null, 2)};
  const ACTION_TIMER_PREFIX = ${JSON.stringify(constants.ACTION_TIMER_PREFIX, null, 2)};
  const ACTION_MAP = ${JSON.stringify(constants.ACTION_MAP, null, 2)};
  const OBJECT_MAP = ${JSON.stringify(constants.OBJECT_MAP, null, 2)};
  const ENTITY_MAP = ${JSON.stringify(constants.ENTITY_MAP, null, 2)};
  const STATE_MAP = ${JSON.stringify(constants.STATE_MAP, null, 2)};
  const ROLE_SUFFIX_MAP = ${JSON.stringify(constants.ROLE_SUFFIX_MAP, null, 2)};
  const MODIFIER_MAP = ${JSON.stringify(constants.MODIFIER_MAP, null, 2)};
  const PANE_BADGE_MAP = ${JSON.stringify(constants.PANE_BADGE_MAP, null, 2)};

  // 3. Dynamic Regex Templates
  ${templatesCode}

  // 4. Role Morphological Synthesizer
  ${synthesizerCode}

  // 5. Pattern Matcher Engine
  ${matcherCode}

  // 6. Master Translation Dispatcher
  ${dispatcherCode}

  // 7. Safety Bypass & DOM Observer Engine
  ${observerCode}

  // 8. Runtime Initialization
  const translateText = createDispatcher(dictionary, lowerDictionary);
  const observerEngine = createObserverEngine(translateText);
  const { walk, startObserver, init } = observerEngine;

  init();

  // 9. Global CommonJS Exports for testing & verification
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
      dictionary,
      lowerDictionary,
      DYNAMIC_TEMPLATES,
      constants: {
        UNIT_MAP_CN,
        ACTION_TIMER_PREFIX,
        ACTION_MAP,
        OBJECT_MAP,
        ENTITY_MAP,
        STATE_MAP,
        ROLE_SUFFIX_MAP,
        MODIFIER_MAP,
        PANE_BADGE_MAP
      },
      normalize,
      formatDur,
      synthesizeRole,
      matchDynamicPatterns,
      translateText,
      createDispatcher,
      isMonacoListRowBypassed,
      isBypassedElement,
      isBypassedNode,
      walk,
      startObserver,
      createObserverEngine
    };
  }
})();
`;

  // 4. 将包含中文字符的全部代码转换为纯 7-bit ASCII \uXXXX
  const fullCode = payloadBanner + clientTemplate;
  const asciiCode = toAsciiUnicode(fullCode);

  // 5. 校验转换后的文件是否 100% 纯 7-bit ASCII
  for (let i = 0; i < asciiCode.length; i++) {
    const code = asciiCode.charCodeAt(i);
    if (code > 127) {
      console.error(`[FATAL] Non-ASCII byte detected at pos ${i}: charCode=${code}`);
      process.exit(1);
    }
  }

  if (!fs.existsSync(distDir)) {
    fs.mkdirSync(distDir, { recursive: true });
  }

  fs.writeFileSync(outputFile, asciiCode, 'ascii');
  const stat = fs.statSync(outputFile);

  console.log(`\n[SUCCESS] dist/patch-payload.js successfully generated!`);
  console.log(`- Target: ${outputFile}`);
  console.log(`- File size: ${(stat.size / 1024).toFixed(2)} KB`);
  console.log(`- Character encoding: Pure 7-bit ASCII (CP936/GBK Immune)\n`);
}

if (require.main === module) {
  build();
}

module.exports = { build, toAsciiUnicode };
